version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: redhat
      MYSQL_DATABASE: crm_db
      MYSQL_USER: root
      MYSQL_PASSWORD: redhat
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://root:redhat@db:3306/crm_db
    volumes:
      - .:/app

volumes:
  mysql_data:
